const ProductZara = [
  {
    url: require(`./img/p1.png`),
    title: "Nike",
    description: "Nike Sportswear Futura Luxe",
    price: 1300,
    beforePrice: 1500,
    category: "bag",
    rating: 4,
    id: 0,
  },
  {
    url: require(`./img/p2.png`),
    title: "Nike",
    description: "Nike Sportswear Futura Luxe",
    price: 1300,
    beforePrice: 1700,
    category: "bag",
    rating: 4,
    id: 1,
  },
  {
    url: require(`./img/p3.png`),
    title: "Nike",
    description: "Nike Sportswear Futura Luxe",
    price: 1300,
    beforePrice: "",
    category: "bag",
    rating: 4,
    id: 2,
  },
  {
    url: require(`./img/p4.png`),
    title: "Nike",
    description: "Nike Sportswear Futura Luxe",
    price: 1300,
    beforePrice: "",
    category: "bag",
    rating: 4,
    id: 3,
  },
];
export default ProductZara;
